export enum MicroservicesEnum {
  AUTH_SERVICE = 'AUTH_SERVICE',
  USERS_SERVICE = 'USERS_SERVICE',
  PRESENCE_SERVICE = 'PRESENCE_SERVICE',
  CHAT_SERVICE = 'CHAT_SERVICE',
  FRIEND_REQUEST_SERVICE = 'FRIEND_REQUEST_SERVICE',
}

export enum RabbitMQ_Queues {
  RABBITMQ_AUTH_QUEUE = 'RABBITMQ_AUTH_QUEUE',
  RABBITMQ_USERS_QUEUE = 'RABBITMQ_USERS_QUEUE',
  RABBITMQ_PRESENCE_QUEUE = 'RABBITMQ_PRESENCE_QUEUE',
  RABBITMQ_CHAT_QUEUE = 'RABBITMQ_CHAT_QUEUE',
  RABBITMQ_FRIEND_REQUEST_QUEUE = 'RABBITMQ_FRIEND_REQUEST_QUEUE',
}
